#!/usr/bin/env python3
"""Regenerate index.md from records/ and topics/ frontmatter.

What this script checks and does:
  - Walks every .md under <root>/records/ and reads its frontmatter
    (type, id, title).
  - Walks <root>/topics/*.md and collects pages with type: topic.
  - Rewrites <root>/index.md as a unified entity catalog: a Topics section
    followed by one section per record type, each entry a relative-path
    markdown link.

What this script does NOT check:
  - It does not validate frontmatter against schemas (that is audit.py).
  - It does not verify that links inside record bodies resolve.
  - It does not detect records whose frontmatter fails to parse; those fall
    into an "Unknown" section rather than being flagged as errors.

Dependencies: python3 stdlib only.

Usage:
  python3 rebuild_index.py [--root PATH]

--root defaults to the current working directory and must point at a wiki
workspace containing records/ and topics/ directories.
"""
import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path


def parse_frontmatter(p: Path) -> dict:
    """Line-based frontmatter scan. Intentionally tolerant: a page with
    malformed YAML still gets indexed under whatever keys parse."""
    text = p.read_text(errors='ignore')
    m = re.match(r'---\n(.*?)\n---', text, re.DOTALL)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        kv = re.match(r'^(\w+):\s*(.*)$', line)
        if kv:
            k, v = kv.group(1), kv.group(2).strip()
            v = v.strip('"').strip("'")
            fm[k] = v
    return fm


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--root', default='.',
                    help='Wiki workspace root (default: current directory).')
    args = ap.parse_args()
    root = Path(args.root).expanduser().resolve()

    records_dir = root / 'records'
    topics_dir = root / 'topics'
    if not records_dir.exists():
        print(f"ERROR: {records_dir} does not exist; is --root a wiki workspace?",
              file=sys.stderr)
        return 2

    # Collect all records by type
    by_type = defaultdict(list)
    for p in records_dir.rglob('*.md'):
        fm = parse_frontmatter(p)
        t = fm.get('type', 'Unknown')
        by_type[t].append((p, fm))

    # Collect topics
    topics = []
    if topics_dir.exists():
        for p in sorted(topics_dir.glob('*.md')):
            if p.name.lower() == 'readme.md':
                continue
            fm = parse_frontmatter(p)
            if fm.get('type') == 'topic':
                topics.append((p, fm))

    total = sum(len(v) for v in by_type.values())
    n_types = len(by_type)

    lines = []
    lines.append("# Index")
    lines.append("")
    lines.append(f"Unified entity catalog: **{total} Records** across "
                 f"{n_types} entity classes.")
    lines.append("")
    lines.append("> Regenerated by `rebuild_index.py`. Do not hand-edit.")
    lines.append("")
    lines.append("## How to use")
    lines.append("")
    lines.append("- Specific document? Find the entity class below; jump to the Record.")
    lines.append("- Cross-cutting question? Skim **Topics** first.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"## Topics ({len(topics)})")
    lines.append("")
    for p, fm in topics:
        title = fm.get('title', p.stem)
        lines.append(f"- [{title}](topics/{p.name})")
    lines.append("")
    lines.append("---")
    lines.append("")

    # One section per record type, alphabetical. The reference system used a
    # hand-curated section ordering; alphabetical is the generic equivalent.
    for t in sorted(by_type):
        items = by_type[t]
        items.sort(key=lambda x: x[1].get('id', x[0].stem))
        lines.append(f"## {t} ({len(items)})")
        lines.append("")
        for p, fm in items:
            rec_id = fm.get('id', p.stem)
            title = fm.get('title', '')
            rel = p.relative_to(root)
            # Truncate long titles to keep the index compact
            if len(title) > 130:
                title = title[:127] + '...'
            if title:
                lines.append(f"- [{rec_id}]({rel}): {title}")
            else:
                lines.append(f"- [{rec_id}]({rel})")
        lines.append("")

    (root / 'index.md').write_text('\n'.join(lines))
    print(f"Wrote index.md: {total} records, {len(topics)} topics")
    if by_type:
        counts = sorted(((t, len(rs)) for t, rs in by_type.items()),
                        key=lambda x: -x[1])
        print(f"By type: {counts}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
